version: "3.9"

services:
  db:
    container_name: db
    image: postgres:15.3-bookworm
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo-db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./scripts:/var/lib/postgresql/scripts

volumes:
  db:
    driver: local
  scripts:
    driver: local
